name: string_contains
description: Package provides light widgets[for Linkify, Clean] and extensions for strings and nullable strings that contain badwords/urls/links/emails/phonenumbers/#hashtags/@mentions and others.
version: 1.0.0
homepage: https://github.com/betterxio/string_contains
issue_tracker : https://github.com/betterxio/string_contains/issues

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
